apiVersion: v1
kind: Pod
metadata:
  name: k8-readiness-probe
spec:
  containers:
  - name: k8-readiness-probe
    image: k8-readiness-probe:1.0
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/health
      initialDelaySeconds: 5
      periodSeconds: 5
